name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: meta-introspector/checkout@v4
      - name: Dependency Review
        uses: meta-introspector/dependency-review-action@main
